# Generated by Django 5.0.3 on 2024-04-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined_uk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_uk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_uk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff_uk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_uk',
        ),
    ]
