# Generated by Django 5.0.3 on 2024-04-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('annotation', models.CharField(blank=True, max_length=255)),
                ('annotation_en', models.CharField(blank=True, max_length=255, null=True)),
                ('annotation_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('annotation_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(verbose_name='date published')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
